### ISSUE TITLE
Incomplete exception log message in Rhino Agent channel

### ISSUE THREAD

**Issue by LifshesOfer** [savanna-projects/rhino-vscode-extension#55]
The log:

Rhino.Agent Error: 0 : ERR - 2023-03-01 10:42:44.557
    Application: RhinoApi
    Logger     : TextConnector
    LogLevel   : ERROR
    TimeStamp  : 2023-03-01 10:42:44.557
    MachineName: IL2L69X92J3
    Message    : Invoke-TestCase -Key RHINO-01 -Run 2023.03.01.10.42.42.989 = (InternalServerError | Sequence contains no elements)
----------------
- Exception(s) -
----------------
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Average[TSource,TSelector,TAccumulator,TResult](IEnumerable`1 source, Func`2 selector)
   at Rhino.Api.Extensions.RhinoTestCaseExtensions.SetQualityRank(RhinoTestCase testCase, RhinoConfiguration configuration)
   at Rhino.Api.Engine.Extensions.EngineExtensions.InvokeTestCaseTeardown(RhinoTestCase testCase, RhinoConfiguration configuration, WebAutomation automation, OrbitResponse response)
   at Rhino.Api.Engine.RhinoAutomationEngine.InvokeSingle(WebAutomation automation, RhinoTestCase testCase)
   at Rhino.Api.Engine.RhinoAutomationEngine.<>c__DisplayClass35_0.<Invoke>b__0(RhinoTestCase i)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Rhino.Api.RhinoConnector.Invoke(RhinoAutomationEngine automationEngine, RhinoTestCase testCase)
   at Rhino.Api.RhinoConnector.<>c__DisplayClass57_0.<Invoke>b__0(Int32 _)

is written as:

timestamp:   2023-03-01 10:42:44.557
level:       ☢ ERROR
application: RhinoApi
logger:      TextConnector
message:     Invoke-TestCase -Key RHINO-01 -Run 2023.03.01.10.42.42.989 = (InternalServerError | Sequence contains no elements)

**Comment by gravity-api** [comment]
fixed
